obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.15, 0.15], [-0.15, 0.15], [-0.15, -0.15], [0.15, -0.15]]
inflation_radius: 0.55

observation_sources: lidar

lidar: {sensor_frame: lidar, data_type: LaserScan, topic: lidar/scan, marking: true, clearing: true}
